---
#[executor]
#172.17.0.4 ansible_connection=ssh ansible_user=jenkins ansible_ssh_private_key_file=~/.ssh/ssh_slave
#ansible_become=True
all:
 children:
  webapp:
   hosts:
    web1:
    web2:
    web3:

  nginx:
   hosts:
    nginx_balancer:
